# This is the default config file for ExampleMod.
# This file should not be modified manually. Edit the .properties file in the config folder in the .minecraft folder instead!
#
mixin.test2=false
mixin.test3=true
mixin.test4=true
mixin.test5=true
mixin.test5.test5_1=true
mixin.test5.test5_2=true
